name: 'Kustomize Image Tag Updater'
description: 'A Github action to automatically update K8s configuration files with the new image tag specified'
author: 'Antonio Gomez Navarro'
inputs:
  repo-url:
    required: true
    description: 'URL of the repository containing the kubernetes manifests'
  new-image:
    required: true
    description: 'Image name with the new tag'
  registry: 
    required: false
    description: 'URL of the registry used to store the image'
    default: 'ghcr.io'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository'
  ssh-key:
    required: false
    description: 'SSH key used to fetch the repository'
  kustomize-path:
    required: false
    description: 'Path to the folder where kustomization.yaml is stored'
    default: 'manifests'
runs:
  using: "composite"
  steps:
    - name: Clone the repository to be updated
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo-url }}
        token: ${{ inputs.token }}
        ssh-key: ${{ ssh-key }}
        path: ./tmp

    - name: Execute image tag updater script
      run: |
        cd tmp/${{ inputs.kustomize-path }}
        echo "$(pwd)"
        ${{ github.action-path }}/kustomize-tag-updater.sh {{ inputs.registry }} {{ inputs.new-image }}
      shell: bash
