name: 'Kustomize Image Tag Updater'
description: 'A Github action to automatically update K8s configuration files with the new image tag specified'
author: 'Antonio Gomez Navarro'
inputs:
  repo:
    required: true
    description: 'URL of the repository containing the kubernetes manifests'
  image:
    required: true
    description: 'Name of the image to be update'
  tag:
    required: true
    description: 'New tag assigned to the image'
  registry: 
    required: false
    description: 'URL of the registry used to store the image'
    default: 'ghcr.io'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository'
  ssh-key:
    required: false
    description: 'SSH key used to fetch the repository'
  kustomize-path:
    required: false
    description: 'Path to the folder where kustomization.yaml is stored'
    default: 'manifests'
runs:
  using: "composite"
  steps:
    - name: Clone the repository to be updated
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo-url }}
        token: ${{ inputs.token }}
        ssh-key: ${{ inputs.ssh-key }}
        path: ./tmp

    - name: Execute image tag updater script
      run: |
        cd tmp/${{ inputs.kustomize-path }}
        echo "Installing Kustomize"
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        echo "Editing kustomization.yaml with new image tag..."
        ./kustomize edit set image {{ inputs.image }}={{ inputs.image }}:{{ inputs.tag }}
        rm kustomize
        echo "Pushing changes to repo..."
        git commit . && git push
      shell: bash
